- name: Bragi
  instr: f8588A
  mode: LAN
  address: 10.205.93.34
  port: '3490'
  gpib: '6'
- name: "V\xED\xF0arr"
  instr: f5730A
  mode: LAN
  address: 10.205.93.24
  port: '3490'
  gpib: '10'
- name: Sigurd
  instr: f8588A
  mode: LAN
  address: 10.205.93.63
  port: '3490'
  gpib: '3'
- name: "Gr\xEDmhildr"
  instr: f5790b
  mode: LAN
  address: 10.205.95.238
  port: '3490'
  gpib: '5'
- name: Mikkel
  instr: f5730A
  mode: LAN
  address: 10.205.93.24
  port: '3490'
  gpib: '5'
- name: Sigtrygr
  instr: f8588A
  mode: LAN
  address: 10.205.92.63
  port: '3490'
  gpib: '6'
- name: Dmitri
  instr: f5730A
  mode: LAN
  address: 10.205.93.101
  port: '3490'
  gpib: '3'
